# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# import sphinx_bootstrap_theme

# -- Project information -----------------------------------------------------
 
project = 'MathSys Users Handbook'
copyright = '2022, Δημήτρης Καλοψικάκης'
author = 'Δημήτρης Καλοψικάκης'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autosectionlabel',
    'sphinx.ext.graphviz',
]
autosectionlabel_prefix_document = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'el'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'
# html_theme = 'sphinxdoc'
# html_theme = 'alabaster'
# html_theme = 'python_docs_theme'
# html_theme = 'sphinx_documatt_theme'
# html_theme = 'bootstrap'
# html_theme_path = sphinx_bootstrap_theme.get_html_theme_path()

# ### For alabaster
# sidebar_width = 500
# page_width = 1000

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']


html_title = ''

latex_documents = [
    ('index', 'MathSysHandbook.tex', 'Τεκμηρίωση Υπολ. Συστημάτων και Υπηρεσιών', f'Δημήτρης Καλοψικάκης', 'howto', True),
    ]

numfig = True

latex_engine = 'xelatex'
latex_show_pagerefs = True
#latex_show_urls = 'footnote'
# latex_elements = {
#     'preamble':r'''
# %\setmainfont[Mapping=tex-text]{GFS Artemisia}
# \setmainfont[Mapping=tex-text]{GFS Didot}
# %\setmainfont[Mapping=tex-text]{GFS Neohellenic}
# %\setmainfont[Mapping=tex-text]{Comic Neue}
# %\setmainfont[Mapping=tex-text]{GFS Solomos}
# %\setmainfont[Mapping=tex-text]{DejaVu Sans}
# '''
#     }

latex_elements = {
    'preamble' : r'''
\usepackage{bbm}
\usepackage{amsmath}
\usepackage{amsfonts}
    '''
    }
